### ISSUE TITLE
Deploy Script

### ISSUE THREAD

**Issue by MGatner** [codeigniter4projects/website#134]
Consider moving the deployment to a separate file (like **.github/scripts/deploy.sh**) and having the GitHub Action workflow call that instead.

**Comment by kenjis** [comment]
For what? To deploy manually (if you have the access key)?
https://github.com/codeigniter4projects/website/blob/7d8d48af5769ceecf22cfa4cac812b08394f85f3/.github/workflows/deploy.yml#L47-L71

**Comment by kenjis** [comment]
I sent #437, but I noticed the script is not so good.
Because the `writable` folder is not persistent.
