### ISSUE TITLE
fix logotype on mobile

### ISSUE THREAD

**Issue by Arhell** [codeigniter4projects/website#162]
![03-12-2021 17-47-42](https://user-images.githubusercontent.com/26163841/144631500-fdb7e80b-09cc-451a-8429-000fdb40f094.jpg)

**Comment by demyr17** [comment]
Actually it was fixed before and I see no error when I try both on mobile and Chrome tools now.

**Comment by Arhell** [comment]
Valid for at least iPhone 5. I'll fix it.
On my phone, it will also climb a little bit
