### ISSUE TITLE
update icon links on mobile

### ISSUE THREAD

**Issue by Arhell** [codeigniter4projects/website#173]
now
![13-12-2021 04-50-21](https://user-images.githubusercontent.com/26163841/145744870-a9792f1f-8fb2-4ce3-ac25-dfadd58627fd.jpg)
to do
![13-12-2021 04-51-02](https://user-images.githubusercontent.com/26163841/145744913-26f40b3d-45d3-4ce8-98ff-44aa4783c9dd.jpg)

**Comment by MGatner** [comment]
That still looks a little weird. I like the left alignment, but can these be justified so they are spread evenly?

**Comment by Arhell** [comment]
> That still looks a little weird. I like the left alignment, but can these be justified so they are spread evenly?
![15-12-2021 00-56-10](https://user-images.githubusercontent.com/26163841/146092619-b5138bc7-88d3-4ad9-978a-5c1bb309c848.jpg)
?
