### ISSUE TITLE
CI4 Download button should link to codeigniter4/framework

### ISSUE THREAD

**Issue by kenjis** [codeigniter4projects/website#203]
Now it links to https://api.github.com/repos/codeigniter4/CodeIgniter4/zipball/v4.1.7
`codeigniter4/CodeIgniter4` is the development repository.

See https://www.codeigniter.com/download

**Comment by MGatner** [comment]
@codeigniter4projects/website

**Comment by MGatner** [comment]
Pushed to production, confirmed the download link is now correct.
<img width="744" alt="Screen Shot 2022-09-08 at 9 50 09 AM" src="https://user-images.githubusercontent.com/17572847/189139650-394e6cff-8258-4514-978b-3e80a54ac2cc.png">

**Comment by kenjis** [comment]
Finally! Thanks.

**Comment by MGatner** [comment]
Now that the automated deposit script appears to be working we should be able to have a much faster release pipeline. Anything that needs to go live just becomes a PR from develop => master.
