### ISSUE TITLE
Dependabot in Top Contributors

### ISSUE THREAD

**Issue by kenjis** [codeigniter4projects/website#208]
It may be true that Dependabot is a top contributor,
but is it intentional?

https://codeigniter.com/contribute
our Revised Website
![Screenshot 2022-01-24 14 37 58](https://user-images.githubusercontent.com/87955/150727867-13fb651d-75dc-4312-b224-9ea6311aa85c.png)

**Comment by MGatner** [comment]
Probably a good idea to exclude it, given especially that it contributes 0 actual code.
