### ISSUE TITLE
 Clear documentation text

### ISSUE THREAD

**Issue by kenjis** [codeigniter4projects/website#209]
It is the same as **Exceptional performance**.

> Clear documentation
CodeIgniter consistently outperforms most of its competitors. 
https://codeigniter.com/

**Comment by kenjis** [comment]
This is closed, and the fix is merged, but the site is not updated.
https://codeigniter.com/

**Comment by MGatner** [comment]
@lonnieezell has worked on some auto-deploy scripts but I don't think they are fully functional. I think they are also only triggered on merges to `master`.

**Comment by kenjis** [comment]
Yes. 
https://github.com/codeigniter4projects/website/blob/9b1ce52d0807bcc00e346a02738b086c746260b4/.github/workflows/deploy.yml#L5

When and how do we merge into master?

**Comment by MGatner** [comment]
I think Lonnie was hoping to have our new scripts and server ready before the next release. @lonnieezell ?
