### ISSUE TITLE
Star and Fork numbers are too small

### ISSUE THREAD

**Issue by kenjis** [codeigniter4projects/website#327]
![Screenshot 2022-11-08 11 33 17](https://user-images.githubusercontent.com/87955/200460897-92878134-4b9a-481e-9b19-95d073100353.png)
https://codeigniter.com/

**Comment by MGatner** [comment]
Weird! It used to be correct. This comes from **app/Libraries/GitHub.php** in `getRepos()` which is an API call.

**Comment by MGatner** [comment]
Ah, it is because we are using `CodeIgniter4/framework` but all our stars and forks are on `CodeIgniter4/CodeIgniter4`. 

![image](https://user-images.githubusercontent.com/17572847/200812641-9c8fe9c3-5e33-4f20-afb4-9bbe87319c39.png)

**Comment by demyr17** [comment]
Well, it was set as 11px on line 503 in the css file and I think we can increase it by 1px to 12px.

**Comment by kenjis** [comment]
I sent a PR #332
