### ISSUE TITLE
Invalid request (Unsupported SSL request) on Localhost

### ISSUE THREAD

**Issue by AmirHosseinMoloudi** [codeigniter4projects/website#386]
Hi.

I just cloned this project on my own pc and then used "php spark serve" to test it.
but the problem is, whenever I try to access it through "http://localhost:8080/", it redirects me to "https://localhost:8080/" and then the browser shows "This site can’t be reached-localhost refused to connect-ERR_CONNECTION_REFUSED" and also the console keeps saying "Invalid request (Unsupported SSL request)"

I double-ckecked config files, htaccess and also php serve arguments but nothing seems wrong!

Thanks in advance for your attention.

**Comment by datamweb** [comment]
Hi,
If you want to access without SSL, Set `$forceGlobalSecureRequests = false`.
https://github.com/codeigniter4projects/website/blob/855dc78202a5445c4c5f7f097a1097d323ff9c68/app/Config/App.php#L137

**Comment by AmirHosseinMoloudi** [comment]
> Hi, If you want to access without SSL, Set `$forceGlobalSecureRequests = false`.
> 
> https://github.com/codeigniter4projects/website/blob/855dc78202a5445c4c5f7f097a1097d323ff9c68/app/Config/App.php#L137

Tnx Man

**Comment by kenjis** [comment]
I sent PR #387 to fix README:
https://github.com/codeigniter4projects/website/blob/bede17ba383dbbf0ea46bbc444a13a1306c6e400/README.md#installation
